### ISSUE TITLE
Initial values

### ISSUE THREAD

**Issue by IanaKhitsko** [AndrianPoida/euro-diffusion#8]
https://github.com/AndrianPoida/euro-diffusion/blob/8e6a2cded47cabd091b5eb3b0d62a5abc7b4b175/src/entities/country.ts#L9-L13

I'm not a TS expert, but which will be number attributes initial values?

**Comment by AndrianPoida** [comment]
Initial values will be 'undefined'. Actual values are assigning to them in a constructor.
