### ISSUE TITLE
Public/private methods

### ISSUE THREAD

**Issue by IanaKhitsko** [AndrianPoida/euro-diffusion#9]
https://github.com/AndrianPoida/euro-diffusion/blob/8e6a2cded47cabd091b5eb3b0d62a5abc7b4b175/src/entities/country.ts#L22

Any private/public methods classifiers all over the code?

**Comment by AndrianPoida** [comment]
Fixed. Added private classifiers to all methods which are used only inside the class. Public classifier assigning to method/variable automatically if no classifier was specified.
